### ISSUE TITLE
Cindermote wont drop additional seeds when harvested.

### ISSUE THREAD

**Issue by MaragretRLautzenhiser** [Voxel-Friend/Rustic-Thaumaturgy#9]
Checking the config, it looks like there is by default a 20% chance for the Rustic Thaumaturgy crops to drop a second seed when harvested. Repeated testing has found that at least one, the cindermote, will never drop additional seeds when harvested.

**Comment by Voxel-Friend** [comment]
There is not, there is a 20% chance for the crop to drop a second crop, not seed.

**Comment by Voxel-Friend** [comment]
Actually, it's a 10% at that:

    @Comment({"Percent chance to get an crop"})
    @RangeInt(min = 0, max = 100)
    public static int cropChance = 100;

    @Comment({"Percent chance to get a second crop"})
    @RangeInt(min = 0, max = 100)
    public static int secondCropChance = 10;

    @Comment({"Percent chance to get a seed drop"})
    @RangeInt(min = 0, max = 100)
    public static int seedChance = 100;

    @Comment({"Percent chance to get a second seed drop"})
    @RangeInt(min = 0, max = 100)
    public static int secondSeedChance = 0;

**Comment by Voxel-Friend** [comment]
Relevant Code:
https://github.com/Voxel-Friend/Rustic-Thaumaturgy/blob/master/src/main/java/com/github/voxelfriend/rusticthaumaturgy/configuration/RTConfiguration.java#L20
